name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:     # allows manual triggering

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, languages
          template: classic
          config_timezone: Asia/Kolkata
