name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */2 * * *"  # Every 2 hours
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Base sections
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # Template
          template: terminal

          # Output file and commit
          output_action: commit
          output_action_commit_message: "📊 Update GitHub Metrics"

          # Plugin: Languages
          plugin_languages: |
            ignored: html, css
            limit: 8
            threshold: 2%

          # Plugin: Coding habits
          plugin_habits: |
            from: 200
            days: 14
            charts: true
            charts_type: graph

          # Plugin: Calendar
          plugin_isocalendar: yes

          # Plugin: Lines of code
          plugin_lines: yes

          # Plugin: Achievements
          plugin_achievements: |
            threshold: C
            display: compact

          # Plugin: Topics
          plugin_topics: |
            sort: stars
            limit: 15

          # Plugin: Stargazers and follow-up
          plugin_stargazers: yes
          plugin_followup: yes

          # Plugin: Stars
          plugin_stars: yes
