name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */2 * * *"  # Runs every 2 hours
  workflow_dispatch:       # Allows manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub Token stored in repository secrets
          token: ${{ secrets.METRICS_TOKEN }}

          # Base sections
          base: header, activity, community, repositories, metadata

          # Layout + Timezone
          config_timezone: Asia/Kolkata
          config_order: |
            base.header
            base.activity
            base.community
            base.repositories
            base.metadata
            languages
            isocalendar
            habits
            stars
            topics
            lines
            achievements
            stargazers
            followup

          # Template theme (you can change to "classic" if you prefer)
          template: terminal

          # Plugins
          plugin_languages: yes
          plugin_languages.ignored: html, css
          plugin_languages.limit: 8
          plugin_languages.threshold: 2%

          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits.from: 200
          plugin_habits.days: 14
          plugin_habits.charts_type: graph
          plugin_lines: yes
          plugin_topics: yes
          plugin_topics.sort: stars
          plugin_topics.limit: 15
          plugin_achievements: yes
          plugin_achievements.threshold: C
          plugin_achievements.display: compact
          plugin_stars: yes
          plugin_stargazers: yes
          plugin_followup: yes

          # Output file will be committed to repo
          output_action: commit
          output_action_commit_message: "📊 Update GitHub Metrics"
